version: '3.8'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "YES"
      MSSQL_SA_PASSWORD: "2Secure*Password2"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  rms-api:
    build: .
    ports:
      - "5000:80"
